version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pwa
      MYSQL_DB_NAME: pwa
      MYSQL_USER: pwa
      MYSQL_PASSWORD: pwa
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"

  local:
    container_name: pwa
    image: pwa
    build:
      context: .
    volumes:
      - .:/code
      - /var/www/media:/media
      - /var/www/static:/static
    environment:
      - "PORT:8000"
      - "DJANGO_SECRET_KEY=1234"
      - "DJANGO_FCM_API_KEY=1234"
      - "DJANGO_DB_HOST=mysql"
    depends_on:
      - mysql
    ports:
    - "8000:8000"
    tty: true
