# Generated by Django 3.1.7 on 2021-03-04 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('added_on', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('style', models.CharField(choices=[('electro', 'Electro')], max_length=256)),
                ('file', models.FileField(upload_to='')),
                ('added_on', models.DateField(auto_now=True)),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to=settings.AUTH_USER_MODEL)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='api.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('added_on', models.DateField(auto_now=True)),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('sounds', models.ManyToManyField(to='api.Sound')),
            ],
        ),
    ]
