# Generated by Django 3.1.7 on 2021-03-11 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='playlistfollowing',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.playlist'),
        ),
        migrations.AlterField(
            model_name='playlistlike',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='api.playlist'),
        ),
        migrations.AlterField(
            model_name='soundlike',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='api.sound'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sound',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.musicstyle'),
        ),
        migrations.DeleteModel(
            name='MusicStyles',
        ),
    ]
