# Generated by Django 3.1.7 on 2021-03-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210311_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='album',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
    ]
