# Generated by Django 3.2 on 2021-04-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='added_by',
        ),
    ]
